import { v4 as uuid } from 'uuid';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: 'Súp Lơ',
    imageSrc: ['/Assets/products/cauliflower.jpg'],
    price: 250,
    quantity: '1 kg',
    inStock: true,
    rating: 3,
    categoryName: 'Củ',
    discount: 15,
  },
  {
    _id: uuid(),
    title: 'Đậu Xanh',
    imageSrc: ['/Assets/products/green-peas.jpg'],
    price: 144,
    quantity: '1 kg',
    inStock: true,
    rating: 4,
    categoryName: 'Hạt',
    discount: 4,
  },
  {
    _id: uuid(),
    title: 'Hồng Xiêm',
    imageSrc: ['/Assets/products/sapodilla.jpg'],
    price: 96,
    quantity: '500 g',
    inStock: true,
    rating: 3,
    categoryName: 'Trái cây',
    discount: 4,
  },
  {
    _id: uuid(),
    title: 'Dừa',
    imageSrc: ['/Assets/products/coconut.jpg'],
    price: 23,
    quantity: '1 kg',
    inStock: true,
    rating: 2,
    categoryName: 'Trái cây',
    discount: 3,
  },
  {
    _id: uuid(),
    title: 'Trứng',
    imageSrc: ['/Assets/products/egg.jpg'],
    price: 75,
    quantity: '12 quả',
    inStock: true,
    rating: 1,
    categoryName: 'Thịt và trứng',
    discount: 6,
  },
  {
    _id: uuid(),
    title: 'Gà rút xương',
    imageSrc: ['/Assets/products/boneless.jpg'],
    price: 214.7,
    quantity: '1 kg',
    inStock: true,
    rating: 1,
    categoryName: 'Thịt và trứng',
    discount: 10,
  },
  {
    _id: uuid(),
    title: 'Lúa Mì Sharbati',
    imageSrc: ['/Assets/products/wheat.jpg'],
    price: 56,
    quantity: '1 kg',
    inStock: true,
    rating: 3,
    categoryName: 'Ngũ cốc',
    discount: 5,
  },
  {
    _id: uuid(),
    title: 'Muối',
    imageSrc: ['/Assets/products/salt.jpg'],
    price: 15,
    quantity: '1 kg',
    inStock: true,
    rating: 4,
    categoryName: 'Ngũ cốc',
    discount: 2,
  },
];
